[package]
name = "heimdall-cli"
version = "0.1.11"
edition = "2021"
description = "A simple hotkey daemon. Primarily tested on MacOS"
homepage = "https://github.com/uzaaft/heimdall"
documentation = "https://github.com/uzaaft/heimdall"
repository = "https://github.com/uzaaft/heimdall"
license = "MIT"

[[bin]]
name = "heim"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1" }
global-hotkey = "0.6"
serde = { version = "1" }
toml = { version = "0.8", default-features = false, features = ["parse"] }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "fmt",
  "env-filter",
] }
winit = { version = "0.30", default-features = false }
fs4 = { version = "0.11", features = ["sync"], default-features = false }
